name: Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. 安装 Node + pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: corepack enable
      - run: pnpm install

      # 3. 编译
      - run: pnpm build

      # 4. 上传构建产物（存储在 workflow 内部）
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist  # 这里改成你的实际构建输出目录

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # 5. 创建 Release 并上传产物
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
